# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  webapi:
    build:
      context: "C:\\Users\\patty\\Downloads\\DOC"
      dockerfile: "Backend/WebApi/Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebApi.dll"
    environment: {}
    image: "webapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\patty\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\patty\\Downloads\\DOC\\Backend\\WebApi:/app:rw"
    - "C:\\Users\\patty\\Downloads\\DOC\\Backend:/src:rw"
    working_dir: "/app"
